- name: Ensure apt-transport-https is installed
  apt:
    name: [apt-transport-https, gpg]

- name: Install carbon-clickhouse service
  apt:
    name: carbon-clickhouse=0.11.0

- name: Create log directory
  file:
    path: /var/log/app/carbon-clickhouse
    state: directory

- name: Copy carbon-clickhouse configurations
  copy:
    src: configs/carbon-clickhouse.conf
    dest: /etc/carbon-clickhouse/
  notify:
    - Restart carbon-clickhouse

- name: Enable & start carbon-clickhouse service
  systemd:
    name: carbon-clickhouse
    state: started
    enabled: yes
    daemon_reload: yes